### ISSUE TITLE
Occasionally see `running` `Task`s without a `CLAIMS` relationship to a `ComputeServiceRegistration`

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/alchemiscale#123]
After some execution time, with compute service instances killed at random times, we've seen some `Task`s with status `running` despite having now `CLAIMS` relationship to a `ComputeServiceRegistration`. 

It is unclear under what conditions this can happen, as the deregistration and expiration queries should reset the status to `waiting` before the claiming `ComputeServiceRegistration` is removed along with its relationships.

**Comment by dotsdl** [comment]
This isn't critical in most cases, as users can always create new tasks or reset these `running` tasks to `waiting` themselves, but it is worth identifying and resolving the root cause.

**Comment by dotsdl** [comment]
Perhaps we need to be doing a [FOREACH](https://neo4j.com/docs/cypher-manual/4.4/clauses/foreach/) when setting task status back to `waiting` in the deregister/expire methods?

**Comment by dotsdl** [comment]
Seeing this repeatedly occur on many tasks on the alchemiscale.org instance. Will use this opportunity to try to identify the underlying issue so we can resolve this one.

**Comment by dotsdl** [comment]
Observed the following in `alchemiscale.org` logs when this problem occurs:
```
docker-alchemiscale-compute-API-1  | RuntimeError: coroutine raised StopIteration
docker-alchemiscale-compute-API-1  | [2024-03-26 04:51:34 +0000] [42] [ERROR] Exception in ASGI application
docker-alchemiscale-compute-API-1  | Traceback (most recent call last):
docker-alchemiscale-compute-API-1  |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
docker-alchemiscale-compute-API-1  |     result = context.run(func, *args)
docker-alchemiscale-compute-API-1  |   File "/tmp/alchemiscale/compute/api.py", line 122, in deregister_computeservice
docker-alchemiscale-compute-API-1  |     compute_service_id_ = n4js.deregister_computeservice(
docker-alchemiscale-compute-API-1  |   File "/tmp/alchemiscale/storage/statestore.py", line 888, in deregister_computeservice
docker-alchemiscale-compute-API-1  |     identifier = next(res)["identifier"]
docker-alchemiscale-compute-API-1  |   File "/opt/conda/lib/python3.10/site-packages/py2neo/cypher/__init__.py", line 110, in __next__
docker-alchemiscale-compute-API-1  |     raise StopIteration()
docker-alchemiscale-compute-API-1  | StopIteration
```

**Comment by dotsdl** [comment]
Examining this more closely, it still remains unclear under what conditions the above exception occurs. There is only one call to [`_deregister()`](https://github.com/openforcefield/alchemiscale/blob/32259d8b16b0bfe9af1fcb346cdc75989b4c4cec/alchemiscale/compute/service.py#L483) in the compute service, and this follows well after its call to [`_register()`](https://github.com/openforcefield/alchemiscale/blob/32259d8b16b0bfe9af1fcb346cdc75989b4c4cec/alchemiscale/compute/service.py#L449), which must return before the service continues starting up. So, the registration *should* exist in the database by the time deregistration is called.

My working hypothesis is that there is some kind of strange race condition occurring in Neo4j itself, in which the deregister call simply doesn't see the state reflected from the register call because it comes too quickly after. This remains a hunch, but it's difficult to pin down because we don't see this behavior in our test suite.

**Comment by dotsdl** [comment]
I believe with release 0.4.0 and the switch to Neo4j 5.x + the official Neo4j Python driver for DB interactions that this issue may no longer be present in practice. Have observed no cases of it in the last ~10 days of production on alchemiscale.org, and it used to be pretty common.

Closing for now; will re-open if the issue re-emerges.
