### ISSUE TITLE
allow setting of `task_status` to "error"

### ISSUE THREAD

**Issue by JenkeScheen** [openforcefield/alchemiscale#236]
We're building a feature in `asap-alchemy` that will allow us to `stop` networks that have tasks `running` or `waiting`. This is useful in cases where we don't care about finishing a network all the way until the last few tasks have finished because we have already collected meaningful results for a prediction deadline. 

We can do this using `alchemiscale.interface.client.set_tasks_status()` after collecting the network's `running`/`waiting` tasks. However, calling `alchemiscale.interface.client.set_tasks_status(tasks, "error")` results in a non-descriptive server-side 500:
```
$ asap-alchemy stop -nk AlchemicalNetwork-e7a[redacted]
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/bin/asap-alchemy", line 8, in <module>
    sys.exit(alchemy())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py", line 487, in stop
    deleted = [ sc_k for sc_k in client._client.set_tasks_status(running + waiting, "error"
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/interface/client.py", line 891, in set_tasks_status
    return self._task_attribute_setter(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/interface/client.py", line 840, in _task_attribute_setter
    return asyncio.run(coro)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/base/client.py", line 45, in _wrapper
    return await f(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/interface/client.py", line 828, in async_request
    scoped_keys = await asyncio.gather(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/interface/client.py", line 854, in _set_task_status
    tasks_updated = await self._post_resource_async(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/base/client.py", line 183, in _wrapper
    return await f(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/base/client.py", line 293, in _wrapper
    return await f(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/base/client.py", line 468, in _post_resource_async
    raise self._exception(
alchemiscale.interface.client.AlchemiscaleClientError: Status Code 500 : Internal Server Error : Internal Server Error
```

Relevant code that is being called is here: https://github.com/choderalab/asapdiscovery/pull/846/files#diff-e7509ca1fb291e683f916c247d51035689ffbd70ca4dd3194e5f3912b1efe088R492

As you can see we have implemented this using "deleted" for now, this works as intended (i.e. sets the tasks to "deleted" status), but is not ideal because then we're not able to revive these tasks if we ever need to in the future.

**Comment by dotsdl** [comment]
Fixed a subtle bug that was giving the nondescript error code you observed in #236. Thanks for finding this one @JenkeScheen!

It's not possible to set a `Task` status from the `AlchemiscaleClient` to any status other than [`waiting`, `invalid`, or `deleted`](https://github.com/openforcefield/alchemiscale/blob/944019c342369f3a11c8ba7016c9e140f5c06320/alchemiscale/interface/api.py#L677-L680). This is intentional: only `Task`s that have actually errored in execution by compute services should get the `error` status applied to them.

As discussed today, using `AlchemiscaleClient.cancel_tasks` is likely what you want here. To cancel a `Task` is the opposite of actioning it, and applies on a per-`AlchemicalNetwork` basis. Canceling a `Task` you no longer care about will drop its `ACTIONS` relationship to the `AlchemicalNetwork`'s `TaskHub`, so it will not be eligible for claiming by a compute service.

Does this work for you?

**Comment by JenkeScheen** [comment]
That works - thanks!

**Comment by dotsdl** [comment]
In that case, it might be better to proceed with using `AlchemiscaleClient.set_tasks_status(tasks, 'deleted')`, then if you'd like to later resume compute on a given `AlchemicalNetwork` and its `Transformation`s, then create and action new `Task`s for that `AlchemicalNetwork`.

Do you see any problems with this approach?

**Comment by dotsdl** [comment]
Another idea: instead of using the output of `get_network_status` for determining if an `AlchemicalNetwork` is "active", perhaps use `get_network_actioned_tasks`. If any `Task`s come back, consider the network "active"; if no `Task`s come back, consider it not "active".

**Comment by dotsdl** [comment]
@JenkeScheen did one of these proposals work for your use case?

**Comment by JenkeScheen** [comment]
Thanks @dotsdl, we ended up using your last suggestion for this PR: https://github.com/choderalab/asapdiscovery/pull/846 and
